### ISSUE TITLE
Can't activate power block while another power-up exists in map

### ISSUE THREAD

**Issue by EdGe7x** [dahrkdaiz/smb3project#12]
[Can't activate power block while another power-up exists in map](https://youtu.be/AByvL8k9Ppk)

Per DahrkDaiz: "A ? block that does not activate means it's a power up block but a power up exists in memory, so it refuses to release its power up until the existing one is gone to prevent overwrite."

This seems like something that might cause frustration/confusion, but also not sure if this is something that can be fixed. If not, feel free to close this issue. 

Analysis:
An overwrite of the power-up in my opinion is probably going to be acceptable in most cases. I mean, if you activate a power-up and leave and don't pick it up then it should be lost/forfeit when the player leaves the screen. Upon activating a new power-up that is likely to be desired in the current scenario/screen, it should kill/terminate the existing power-up that is somewhere else on the map.

Just thinking this through as a series of logical steps...

**Comment by KingKoopa94** [comment]
Agreed with the last part, most of the time when you leave a power, you don't want it anyway.
So having the item overwritten in the memory seems like it would be an okay trade off

**Comment by EdGe7x** [comment]
Also thinking this problem may be compounded if "Keys" are considered power-ups. That could render a level unbeatable if it is killed/overwritten off screen when a new power-up is activated on current screen... toughie!

**Comment by dahrkdaiz** [comment]
I can do this. I actually it was more frustrating to lose a power up from activating a ? block but it seems I was wrong! I'll make it that when a new power up appears (keys are not considered to be power ups), any existing ones will "poof" away.

**Comment by dahrkdaiz** [comment]
Okay that was relatively easy. If a block is about to produce an item and another block happens to be activated during the animation, the first block won't produce anything (but a poof will display). If an existing power up is on screen, it will poof away.

Now, there are only 3 slots dedicated to the block-bump animation and power ups. If somehow 3 blocks are activated at the same time, a 4th block will no activate. However, during my testing, this has never happened.

Also, keys some times use the same slots available to power ups, but will not poof away since they are sometimes essential to progressing.
