### ISSUE TITLE
Graphical glitch using Firefox Mario

### ISSUE THREAD

**Issue by RetroMarine** [dahrkdaiz/smb3project#43]
Cannot confirm this glitch was a direct product of using the fire wave special attack or not, but it happened when I used it to collect a bunch of coins in mid-air in the Stacks of Enemies level.  I was unable to recreate the glitch, but I snapped this pic right after.  Yes, found on most recent rom release.  
![img_2496](https://cloud.githubusercontent.com/assets/6308005/21947346/b8e1f0dc-d9b2-11e6-87a7-0e4bb69a4a13.JPG)

**Comment by dahrkdaiz** [comment]
Yeah, this is a known issue and it basically happens when Mario moves fast instantly in some situations. I've been unable to reproduce this regularly so this may be a known bug that simply makes it through since it doesn't affect game play.  Scrolling out of range of the area and back always fixes it, but I'll keep this opened as a reminder that I need to look at it.

**Comment by RetroMarine** [comment]
Roger Dodger.
